-- Remove campo city e cria tabela de nacionalidades
-- Drop campo city que não será usado
ALTER TABLE leads DROP COLUMN IF EXISTS city;

-- Cria tabela de nacionalidades
CREATE TABLE IF NOT EXISTS nationalities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country TEXT NOT NULL,
  nationality TEXT NOT NULL,
  masculine TEXT,
  feminine TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Adiciona índice para buscas
CREATE INDEX IF NOT EXISTS idx_nationalities_country ON nationalities(country);
CREATE INDEX IF NOT EXISTS idx_nationalities_nationality ON nationalities(nationality);

-- Popular tabela com nacionalidades
INSERT INTO nationalities (country, nationality, masculine, feminine) VALUES
('Afeganistão', 'afegã(o)', 'afegão', 'afegãa'),
('África do Sul', 'sul-africano(a)', 'sul-africano', 'sul-africana'),
('Albânia', 'albanês(esa)', 'albanês', 'albanesa'),
('Alemanha', 'alemã(ão)', 'alemão', 'alemã'),
('Andorra', 'andorrano(a)', 'andorrano', 'andorrana'),
('Angola', 'angolano(a)', 'angolano', 'angolana'),
('Anguila', 'anguilano(a)', 'anguilano', 'anguilana'),
('Antígua e Barbuda', 'antiguano(a)', 'antiguano', 'antiguana'),
('Antilhas Holandesas', 'antilhano(a)', 'antilhano', 'antilhana'),
('Arábia Saudita', 'árabe-saudita', 'árabe-saudita', 'árabe-saudita'),
('Argélia', 'argelino(a)', 'argelino', 'argelina'),
('Argentina', 'argentino(a)', 'argentino', 'argentina'),
('Armênia', 'arménio(a)', 'arménio', 'arménia'),
('Aruba', 'arubano(a)', 'arubano', 'arubana'),
('Austrália', 'australiano(a)', 'australiano', 'australiana'),
('Áustria', 'austríaco(a)', 'austríaco', 'austríaca'),
('Azerbaijão', 'azeri', 'azeri', 'azeri'),
('Bahamas', 'baamiano(a)', 'baamiano', 'baamiana'),
('Bahrein', 'barenita', 'barenita', 'barenita'),
('Bangladesh', 'bangladechiano(a)', 'bangladechiano', 'bangladechiana'),
('Barbados', 'barbadense', 'barbadense', 'barbadense'),
('Bélgica', 'belga', 'belga', 'belga'),
('Belize', 'belizenho(a)', 'belizenho', 'belizenha'),
('Benim', 'benineseo(a)', 'benineseo', 'beninesea'),
('Bermudas', 'bermudense', 'bermudense', 'bermudense'),
('Bielorrússia', 'bielorrusso(a)', 'bielorrusso', 'bielorrussa'),
('Bolívia', 'boliviano(a)', 'boliviano', 'boliviana'),
('Bósnia e Herzegovina', 'bósnio(a)', 'bósnio', 'bósnia'),
('Botswana', 'botsuano(a)', 'botsuano', 'botsuana'),
('Brasil', 'brasileiro(a)', 'brasileiro', 'brasileira'),
('Brunei', 'bruneíno(a)', 'bruneíno', 'bruneína'),
('Bulgária', 'búlgaro(a)', 'búlgaro', 'búlgara'),
('Burquina Fasso', 'burquino(a)', 'burquino', 'burquina'),
('Burundi', 'burundiano(a)', 'burundiano', 'burundiana'),
('Butão', 'butanês(esa)', 'butanês', 'butanesa'),
('Cabo Verde', 'cabo-verdiano(a)', 'cabo-verdiano', 'cabo-verdiana'),
('Camarões', 'camaronês(esa)', 'camaronês', 'camaronesa'),
('Camboja', 'cambojano(a)', 'cambojano', 'cambojana'),
('Canadá', 'canadiano(a)', 'canadiano', 'canadiana'),
('Cazaquistão', 'cazaque', 'cazaque', 'cazaque'),
('Chade', 'chadiano(a)', 'chadiano', 'chadiana'),
('Chile', 'chileno(a)', 'chileno', 'chilena'),
('China', 'chinês(esa)', 'chino', 'china'),
('Chipre', 'cipriota', 'cipriota', 'cipriota'),
('Colômbia', 'colombiano(a)', 'colombiano', 'colombiana'),
('Comores', 'comoriano(a)', 'comoriano', 'comoriana'),
('República do Congo', 'congolês(a)', 'congolês', 'congolesa'),
('Coreia do Norte', 'norte-coreano(a)', 'norte-coreano', 'norte-coreana'),
('Coreia do Sul', 'sul-coreano(a)', 'sul-coreano', 'sul-coreana'),
('Costa do Marfim', 'marfinense', 'marfinense', 'marfinense'),
('Costa Rica', 'costarriquenho(a)', 'costarriquenho', 'costarriquenha'),
('Croácia', 'croata', 'croata', 'croata'),
('Cuba', 'cubano(a)', 'cubano', 'cubana'),
('Curaçau', 'curaçauense', 'curaçauense', 'curaçauense'),
('Dinamarca', 'dinamarquês(esa)', 'dinamarquês', 'dinamarquesa'),
('Djibouti', 'jibutiano(a)', 'jibutiano', 'jibutiana'),
('Dominica', 'dominiquês(esa)', 'dominiquo', 'dominiqua'),
('Egito', 'egípcio(a)', 'egípcio', 'egípcia'),
('El Salvador', 'salvadorenho(a)', 'salvadorenho', 'salvadorenha'),
('Emirados Árabes Unidos', 'emiradense', 'emiradense', 'emiradense'),
('Equador', 'equatoriano(a)', 'equatoriano', 'equatoriana'),
('Eritreia', 'eritreu(ia)', 'eritreu', 'eritreia'),
('Escócia', 'escocês(esa)', 'escocês', 'escocesa'),
('Eslováquia', 'eslovaco(a)', 'eslovaco', 'eslovaca'),
('Eslovênia', 'esloveno(a)', 'esloveno', 'eslovena'),
('Espanha', 'espanhol(a)', 'espanhol', 'espanhola'),
('Estados Federados da Micronésia', 'micronésio(a)', 'micronésio', 'micronésia'),
('Estados Unidos', 'norte-americano(a)', 'norte-americano', 'norte-americana'),
('Estónia', 'estoniano(a)', 'estoniono', 'estoniana'),
('Etiópia', 'etíope', 'etíope', 'etíope'),
('Fiji', 'fijiano(a)', 'fijiano', 'fijiana'),
('Filipinas', 'filipino', 'filipino', 'filipino'),
('Finlândia', 'finlandês(esa)', 'finlandês', 'finlandesa'),
('França', 'francês(esa)', 'francês', 'francesa'),
('Gabão', 'gabonês(a)', 'gabonês', 'gabonesa'),
('Gâmbia', 'gambiano(a)', 'gambiano', 'gambiana'),
('Gana', 'ganês(a)', 'ganês', 'ganesa'),
('Geórgia', 'georgiano(a)', 'georgiano', 'georgiana'),
('Granada', 'granadino(a)', 'granadino', 'granadina'),
('Grécia', 'grego(a)', 'grego', 'grega'),
('Guadalupe', 'guadalupense', 'guadalupense', 'guadalupense'),
('Guam', 'guamês(a)', 'guamês', 'guamesa'),
('Guatemala', 'guatemalteco(a)', 'guatemalteco', 'guatemalteca'),
('Guiana', 'guianês(esa)', 'guianês', 'guianesa'),
('Guiana Francesa', 'guianense', 'guianense', 'guianense'),
('Guiné', 'guineano(a)', 'guineano', 'guineana'),
('Guiné Equatorial', 'guinéu-equatoriano(a)', 'guinéu-equatoriano', 'guinéu-equatoriana'),
('Guiné-Bissau', 'guineense', 'guineense', 'guineense'),
('Haiti', 'haitiano(a)', 'haitiano', 'haitiana'),
('Honduras', 'hondurenho(a)', 'hondurenho', 'hondurenha'),
('Hong Kong', 'honconguês(esa)', 'honconguês', 'honconguesa'),
('Hungria', 'húngaro(a)', 'húngaro', 'húngara'),
('Iêmen', 'iemenita', 'iemenita', 'iemenita'),
('Ilhas Caimã', 'caimanês(a)', 'caimanês', 'caimanesa'),
('Ilhas Cook', 'cookense', 'cookense', 'cookense'),
('Ilhas Feroé', 'faroense', 'faroense', 'faroense'),
('Ilhas Salomão', 'salomonense', 'salomonense', 'salomonense'),
('Ilhas Virgens Americanas', 'virginense', 'virginense', 'virginense'),
('Ilhas Virgens Britânicas', 'virginense', 'virginense', 'virginense'),
('Índia', 'indiano(a)', 'indiano', 'indiana'),
('Indonésia', 'indonésia(o)', 'indonésio', 'indonésia'),
('Inglaterra', 'inglês(esa)', 'inglês', 'inglesa'),
('Irão', 'iraniano(a)', 'iraniano', 'iraniana'),
('Iraque', 'iraquiano(a)', 'iraquiano', 'iraquiana'),
('Irlanda', 'irlandês(a)', 'irlandês', 'irlandesa'),
('Irlanda do Norte', 'norte-irlandês(esa)', 'norte-irlandês', 'norte-irlandesa'),
('Islândia', 'islandês(esa)', 'islando', 'islanda'),
('Israel', 'israelense', 'israelense', 'israelense'),
('Itália', 'italiano(a)', 'italiano', 'italiana'),
('Jamaica', 'jamaicano(a)', 'jamaicano', 'jamaicana'),
('Japão', 'japonês(esa)', 'japonês', 'japonesa'),
('Jordânia', 'jordano(a)', 'jordano', 'jordana'),
('Kiribati', 'quiribatiano(a)', 'quiribatiano', 'quiribatiana'),
('Kosovo', 'kosovar', 'kosovar', 'kosovar'),
('Kuwait', 'kuwaitiano(a)', 'kuwaitiano', 'kuwaitiana'),
('Laos', 'laociano(a)', 'laociano', 'laociana'),
('Lesoto', 'lesotiano(a)', 'lesotiano', 'lesotiana'),
('Letônia', 'letã(o)', 'letão', 'letã'),
('Líbano', 'libanês(a)', 'libanês', 'libanesa'),
('Libéria', 'liberiano(a)', 'liberiano', 'liberiana'),
('Líbia', 'líbio(a)', 'líbio', 'líbia'),
('Liechtenstein', 'listenstainiano(a)', 'listenstainiano', 'listenstainiana'),
('Lituânia', 'lituano(a)', 'lituano', 'lituana'),
('Luxemburgo', 'luxemburguês(a)', 'luxemburguês', 'luxemburguesa'),
('Macau', 'macaense', 'macaense', 'macaense'),
('Macedônia do Norte', 'macedônico(a)', 'macedônico', 'macedônica'),
('Madagáscar', 'malgaxe', 'malgaxe', 'malgaxe'),
('Malásia', 'malaio(a)', 'malaio', 'malaia'),
('Malawi', 'malauiano(a)', 'malauiano', 'malauiana'),
('Maldivas', 'maldivo(a)', 'maldivo', 'maldiva'),
('Mali', 'malinês', 'malinês', 'malinês'),
('Malta', 'maltês(a)', 'maltês', 'maltesa'),
('Marrocos', 'marroquino(a)', 'marroquino', 'marroquina'),
('Martinica', 'martinicano(a)', 'martinicano', 'martinicana'),
('Ilhas Maurícias', 'mauriciano(a)', 'mauriciano', 'mauriciana'),
('Mauritânia', 'mauritano(a)', 'mauritano', 'mauritana'),
('México', 'mexicano(a)', 'mexicano', 'mexicana'),
('Myanmar', 'birmanês(a)', 'birmanês', 'birmanesa'),
('Moçambique', 'moçambicano(a)', 'moçambicano', 'moçambicana'),
('Moldávia', 'moldavo(a)', 'moldavo', 'moldava'),
('Mónaco', 'monegasco(a)', 'monegasco', 'monegasca'),
('Mongólia', 'mongol', 'mongol', 'mongol'),
('Montenegro', 'montenegrino(a)', 'montenegrino', 'montenegrina'),
('Monserrate', 'monserratense', 'monserratense', 'monserratense'),
('Namíbia', 'namibiano(a)', 'namibiano', 'namibiana'),
('Nauru', 'nauruano(a)', 'nauruano', 'nauruana'),
('Nepal', 'nepalês(a)', 'nepalês', 'nepalesa'),
('Nicarágua', 'nicaraguense', 'nicaraguense', 'nicaraguense'),
('Níger', 'nigerino(a)', 'nigerino', 'nigerina'),
('Nigéria', 'nigeriano(a)', 'nigeriano', 'nigeriana'),
('Noruega', 'norueguês(esa)', 'norueguês', 'norueguesa'),
('Nova Caledónia', 'neocaledónio(a)', 'neocaledónio', 'neocaledónia'),
('Nova Zelândia', 'neozelandês(esa)', 'neozelandês', 'neozelandesa'),
('Omã', 'omanense', 'omanense', 'omanense'),
('País de Gales', 'galês(esa)', 'galês', 'galesa'),
('Países Baixos', 'neerlandês(a)', 'neerlandês', 'neerlandesa'),
('Palau', 'palauano(a)', 'palauano', 'palauana'),
('Palestina', 'palestiniano(a)', 'palestiniano', 'palestiniana'),
('Panamá', 'panamenho(a)', 'panamenho', 'panamenha'),
('Papua-Nova Guiné', 'papua', 'papua', 'papua'),
('Paquistão', 'paquistanês(a)', 'paquistanês', 'paquistanesa'),
('Paraguai', 'paraguaio(a)', 'paraguaio', 'paraguaia'),
('Peru', 'peruano(a)', 'peruano', 'peruana'),
('Polinésia Francesa', 'polinésio(a)', 'polinésio', 'polinésia'),
('Polónia', 'polaco(a)', 'polaco', 'polaca'),
('Porto Rico', 'porto-riquenho(a)', 'porto-riquenho', 'porto-riquenha'),
('Portugal', 'português(esa)', 'português', 'portuguesa'),
('Catar', 'catariano(a)', 'catariano', 'catariana'),
('Quênia', 'queniano(a)', 'queniano', 'queniana'),
('Quirguistão', 'quirguiz', 'quirguiz', 'quirguiz'),
('Reino Unido', 'britânico(a)', 'britânico', 'britânica'),
('República Centro-Africana', 'centro-africano(a)', 'centro-africano', 'centro-africana'),
('República Dominicana', 'dominicano(a)', 'dominicano', 'dominicana'),
('República Tcheca', 'tcheco(a)', 'tcheco', 'tcheca'),
('Reunião', 'reunionense', 'reunionense', 'reunionense'),
('Romênia', 'romeno(a)', 'romeno', 'romena'),
('Ruanda', 'ruandês(esa)', 'ruandês', 'ruandesa'),
('Rússia', 'russo(a)', 'russo', 'russa'),
('Samoa', 'samoano(a)', 'samoano', 'samoana'),
('Samoa Americana', 'samoano(a)', 'samoano', 'samoana'),
('Santa Lúcia', 'santa-lucense', 'santa-lucense', 'santa-lucense'),
('São Cristóvão e Nevis', 'são-cristovense', 'são-cristovense', 'são-cristovense'),
('São Marinho', 'são-marinense', 'são-marinense', 'são-marinense'),
('São Tomé e Príncipe', 'são-tomense', 'são-tomense', 'são-tomense'),
('São Vicente e Granadinas', 'são-vicentino(a)', 'são-vicentino', 'são-vicentina'),
('Seicheles', 'seichelense', 'seichelense', 'seichelense'),
('Senegal', 'senegalês(esa)', 'senegalês', 'senegalesa'),
('Serra Leoa', 'serra-leonês(esa)', 'serra-leonês', 'serra-leonesa'),
('Sérvia', 'sérvio(a)', 'sérvio', 'sérvia'),
('Singapura', 'singapuriano(a)', 'singapuriano', 'singapuriana'),
('Síria', 'sírio(a)', 'sírio', 'síria'),
('Somália', 'somali', 'somali', 'somali'),
('Sri Lanka', 'cingalês(esa)', 'cingalês', 'cingalesa'),
('Suazilândia', 'suazi', 'suazi', 'suazi'),
('Sudão', 'sudanês(esa)', 'sudanês', 'sudanesa'),
('Sudão do Sul', 'sul-sudanês(esa)', 'sul-sudanês', 'sul-sudanesa'),
('Suécia', 'sueco(a)', 'sueco', 'sueca'),
('Suíça', 'suíço(a)', 'suíço', 'suíça'),
('Suriname', 'surinamês(esa)', 'surinamês', 'surinamesa'),
('Tailândia', 'tailandês(esa)', 'tailandês', 'tailandesa'),
('Taiwan', 'taiwanês(esa)', 'taiwanês', 'taiwanesa'),
('Tajiquistão', 'tadjique', 'tadjique', 'tadjique'),
('Tanzânia', 'tanzaniano(a)', 'tanzaniano', 'tanzaniana'),
('Timor-Leste', 'timorense', 'timorense', 'timorense'),
('Togo', 'togolês(esa)', 'togolês', 'togolesa'),
('Tonga', 'tonganês(esa)', 'tonganês', 'tonganesa'),
('Trinidad e Tobago', 'trinitário(a)', 'trinitário', 'trinitária'),
('Tunísia', 'tunisiano(a)', 'tunisiano', 'tunisiana'),
('Turcomenistão', 'turcomeno(a)', 'turcomeno', 'turcomana'),
('Turquia', 'turco(a)', 'turco', 'turca'),
('Tuvalu', 'tuvaluano(a)', 'tuvaluano', 'tuvaluana'),
('Ucrânia', 'ucraniano(a)', 'ucraniano', 'ucraniana'),
('Uganda', 'ugandense', 'ugandense', 'ugandense'),
('Uruguai', 'uruguaio(a)', 'uruguaio', 'uruguaia'),
('Uzbequistão', 'uzbeque', 'uzbeque', 'uzbeque'),
('Vanuatu', 'vanuatuense', 'vanuatuense', 'vanuatuense'),
('Vaticano', 'vaticano(a)', 'vaticano', 'vaticana'),
('Venezuela', 'venezuelano(a)', 'venezuelano', 'venezuelana'),
('Vietnã', 'vietnamita', 'vietnamita', 'vietnamita'),
('Zâmbia', 'zambiano(a)', 'zambiano', 'zambiana'),
('Zimbábue', 'zimbabuano(a)', 'zimbabuano', 'zimbabuana');

-- Modifica o campo nationality em leads para ser UUID (foreign key)
ALTER TABLE leads DROP COLUMN IF EXISTS nationality;
ALTER TABLE leads ADD COLUMN nationality_id UUID REFERENCES nationalities(id);
CREATE INDEX IF NOT EXISTS idx_leads_nationality ON leads(nationality_id);

-- Habilita RLS na tabela nationalities
ALTER TABLE nationalities ENABLE ROW LEVEL SECURITY;

-- Policy para leitura pública de nacionalidades
CREATE POLICY "Nationalities são públicas para leitura"
  ON nationalities FOR SELECT
  TO authenticated
  USING (true);
